spring:
  application:
    name: hub-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

kakao:
  api:
    key: ${KAKAO_REST_API_KEY}
    base-url: https://dapi.kakao.com